# Generated by Django 2.0.2 on 2018-02-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180228_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='members',
            new_name='user',
        ),
    ]
