# Generated by Django 2.0.2 on 2018-03-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agencyMessage',
            field=models.TextField(blank=True, null=True, verbose_name='中介留言'),
        ),
        migrations.AddField(
            model_name='project',
            name='isMaterialEnough',
            field=models.BooleanField(default=False, verbose_name='中介材料齐全度'),
        ),
        migrations.AddField(
            model_name='project',
            name='workerMessage',
            field=models.TextField(blank=True, null=True, verbose_name='编写员留言'),
        ),
        migrations.AlterField(
            model_name='project',
            name='createTime',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectState',
            field=models.CharField(blank=True, choices=[('receivedInfo', '收到资料'), ('reportEdit', '报告编写'), ('InfoComplete', '资质材料完善'), ('submit', '入件'), ('investigate', '审批修改'), ('takeEvidence', '取证')], max_length=10, null=True, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.CharField(blank=True, choices=[('newBuilt', '新建'), ('extension', '扩建'), ('removal', '搬迁')], max_length=10, null=True, verbose_name='项目性质'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updateTime',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
