# Generated by Django 2.0.3 on 2018-04-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exhaustGasMaterials',
            field=models.TextField(blank=True, default='[{}]', null=True, verbose_name='废气材料信息'),
        ),
    ]
