# Generated by Django 2.0.3 on 2018-03-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectStatus',
            field=models.CharField(blank=True, choices=[(None, '无'), ('receivedInfo', '收到资料'), ('reportEdit', '报告编写'), ('InfoComplete', '资质材料完善'), ('submit', '入件'), ('investigate', '审批修改'), ('takeEvidence', '取证')], max_length=255, null=True, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.CharField(blank=True, choices=[(None, '无'), ('newBuilt', '新建'), ('extension', '扩建'), ('removal', '搬迁')], max_length=255, null=True, verbose_name='项目性质'),
        ),
    ]
