# Generated by Django 2.0.2 on 2018-03-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180320_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectState',
            field=models.CharField(blank=True, choices=[('none', '无'), ('receivedInfo', '收到资料'), ('reportEdit', '报告编写'), ('InfoComplete', '资质材料完善'), ('submit', '入件'), ('investigate', '审批修改'), ('takeEvidence', '取证')], default='none', max_length=10, null=True, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.CharField(blank=True, choices=[('none', '无'), ('newBuilt', '新建'), ('extension', '扩建'), ('removal', '搬迁')], default='none', max_length=10, null=True, verbose_name='项目性质'),
        ),
    ]
