# Generated by Django 2.0.2 on 2018-02-28 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180228_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='material',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='product',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agency_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_project', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
