# Generated by Django 2.0.3 on 2018-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180407_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='groundwaterArea',
            field=models.TextField(blank=True, null=True, verbose_name='地下水区域'),
        ),
    ]
