# Generated by Django 2.0.2 on 2018-03-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180320_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectState',
            new_name='projectStatus',
        ),
    ]
