# Generated by Django 2.0.3 on 2018-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180407_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='domesticSewageGo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='生活污水去向'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groundwaterArea',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地下水区域'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='fileType',
            field=models.CharField(blank=True, choices=[('businessLicenseFile', '营业执照复印件'), ('idCardFile', '法人身份证复印件'), ('workshopLeaseContractFile', '厂房租赁合同复印件'), ('siteUseFile', '场地使用证明复印件'), ('environmentalProtectionCertificate', '环保证'), ('workshopEastImg', '厂址四至图-东'), ('workshopSouthImg', '厂址四至图-南'), ('workshopWestImg', '厂址四至图-西'), ('workshopNorthImg', '厂址四至图-北'), ('processFlowChart', '工艺流程图'), ('planeLayoutChart', '平面布置图'), ('satelliteInformationChart', '卫星信息图')], max_length=255, null=True, verbose_name='文件类型'),
        ),
    ]
