# Generated by Django 2.0.2 on 2018-03-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180321_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='energyUse',
            new_name='energyUsage',
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.TextField(default='[{}]', null=True, verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='project',
            name='material',
            field=models.TextField(default='[{}]', null=True, verbose_name='材料'),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.TextField(default='[{}]', null=True, verbose_name='产品'),
        ),
    ]
