# Generated by Django 2.0.2 on 2018-03-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180321_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='energyUsage',
            field=models.CharField(choices=[('NG', '天然气'), ('LPG', '液化石油气'), ('none', '无')], max_length=255, null=True, verbose_name='能源使用情况'),
        ),
    ]
