# Generated by Django 2.0.2 on 2018-03-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180321_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='NEIType',
            field=models.CharField(default='[]', max_length=255, null=True, verbose_name='国民经济行业类别及代码'),
        ),
        migrations.AlterField(
            model_name='project',
            name='environmentalEffectclassification',
            field=models.CharField(default='[]', max_length=255, null=True, verbose_name='环境影响评价行业类别'),
        ),
    ]
