# Generated by Django 2.0.2 on 2018-03-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180321_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='emissionStandard',
            field=models.TextField(default='[{"standard":"","pollutant":"","pollutantOptions":[],"emissionMonitoring":"","maximumAllowableEmissionRate":"","maximumAllowableEmissionConcentration":""}]', null=True, verbose_name='废弃排放标准'),
        ),
        migrations.AlterField(
            model_name='project',
            name='environmentalEngineering',
            field=models.TextField(default='[{"project":"环保工程","content":"","use":""}]', null=True, verbose_name='环保工程'),
        ),
    ]
