# Generated by Django 2.0.2 on 2018-03-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180321_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='otherEngineeringData',
            field=models.TextField(default='[{"project":"主体工程","content":"","use":""},{"project":"储运工程","content":"","use":""},{"project":"辅助工程","content":"","use":""},{"project":"公用工程","content":"","use":""}]', null=True, verbose_name='其他工程'),
        ),
    ]
