# Generated by Django 2.0.2 on 2018-03-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180321_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='otherEngineeringData',
            new_name='otherEngineering',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sensitiveInfoAtmosphereData',
            new_name='sensitiveInfoAtmosphere',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sensitiveInfoHouseData',
            new_name='sensitiveInfoHouse',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sensitiveInfoReserveData',
            new_name='sensitiveInfoReserve',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sensitiveInfoVoiceData',
            new_name='sensitiveInfoVoice',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sensitiveInfoWaterData',
            new_name='sensitiveInfoWater',
        ),
    ]
