# Generated by Django 2.0.2 on 2018-03-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180321_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sensitiveInfoAtmosphere',
            field=models.TextField(default='[{"environmentalElements":"大气环境","orientation":"---","distance":"---","environmentalObjective":"《环境空气质量标准》（GB3095-2012）二级标准"}]', null=True, verbose_name='大气环境'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sensitiveInfoHouse',
            field=models.TextField(default='[{"environmentalElements":"","orientation":"","distance":"","environmentalObjective":""}]', null=True, verbose_name='水源保护区环境要素'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sensitiveInfoReserve',
            field=models.TextField(default='[{"environmentalElements":"","orientation":"","distance":"","environmentalObjective":""}]', null=True, verbose_name='居民区环境要素'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sensitiveInfoVoice',
            field=models.TextField(default='[{"environmentalElements":"声环境","orientation":"---","distance":"---","environmentalObjective":""}]', null=True, verbose_name='声环境'),
        ),
    ]
