# Generated by Django 2.0.2 on 2018-03-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180321_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='EAcompanyAddress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='环评单位联系地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='EAcompanyCertificatenumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='环评单位证书编号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='EAcompanyName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='环评公司名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='EAcompanyTelephone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='环评单位联系电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='NEIType',
            field=models.CharField(blank=True, default='[]', max_length=255, null=True, verbose_name='国民经济行业类别及代码'),
        ),
        migrations.AlterField(
            model_name='project',
            name='accommodationNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='职工住宿人数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='项目地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='besideWaterTreatmentPlant',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='是否污水处理厂纳污范围'),
        ),
        migrations.AlterField(
            model_name='project',
            name='businessRange',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='营业执照经营范围'),
        ),
        migrations.AlterField(
            model_name='project',
            name='constructionCompanyName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='建设单位名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='constructionScale',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='项目规模'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contacts',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='corporateId',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='法人身份证'),
        ),
        migrations.AlterField(
            model_name='project',
            name='corporateName',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='法人代表姓名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dayWorkTime',
            field=models.FloatField(blank=True, null=True, verbose_name='日工作时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dinningNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='员工吃饭人数（人）'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domesticSewageEmissionStandards',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='生活污水环境影响分析'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domesticSewageEnvironmentImpactAnalysis',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='生活污水环境影响分析'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domesticSewageGo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='生活污水去向'),
        ),
        migrations.AlterField(
            model_name='project',
            name='east',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='东 '),
        ),
        migrations.AlterField(
            model_name='project',
            name='energyUsage',
            field=models.CharField(blank=True, choices=[('NG', '天然气'), ('LPG', '液化石油气'), ('none', '无')], max_length=255, null=True, verbose_name='能源使用情况'),
        ),
        migrations.AlterField(
            model_name='project',
            name='environmentalEffectclassification',
            field=models.CharField(blank=True, default='[]', max_length=255, null=True, verbose_name='环境影响评价行业类别'),
        ),
        migrations.AlterField(
            model_name='project',
            name='environmentalProtectionInvestment',
            field=models.FloatField(blank=True, null=True, verbose_name='环保投资（万元）'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.TextField(blank=True, default='[{}]', null=True, verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='project',
            name='floorSpace',
            field=models.FloatField(blank=True, null=True, verbose_name='占地面积（m2)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groundwaterArea',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地下水区域'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groundwaterBodyNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地下水水体编号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groundwaterQualityStandard',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地下水质量标准'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groundwaterType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地下水类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='investmentTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='投产时间(年)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='project',
            name='longtitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='project',
            name='managementSpace',
            field=models.FloatField(blank=True, null=True, verbose_name='经营面积(m2)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='material',
            field=models.TextField(blank=True, default='[{}]', null=True, verbose_name='材料'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nameAbbreviation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称缩写'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nonAccommodationNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='职工非住宿人数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='north',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='北'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pollutantHoldingWaterBody',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='纳污水体'),
        ),
        migrations.AlterField(
            model_name='project',
            name='postalCode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.TextField(blank=True, default='[{}]', null=True, verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sensitivePointDistance',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='敏感点距离'),
        ),
        migrations.AlterField(
            model_name='project',
            name='societyCreditcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='统一社会信用代码'),
        ),
        migrations.AlterField(
            model_name='project',
            name='soundEnvironmentStandard',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='声环境质量标准'),
        ),
        migrations.AlterField(
            model_name='project',
            name='south',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='南'),
        ),
        migrations.AlterField(
            model_name='project',
            name='specialOptionForSewageTreatmentWorks',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='污水处理厂特别选项'),
        ),
        migrations.AlterField(
            model_name='project',
            name='surfaceWaterFunction',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地表水功能'),
        ),
        migrations.AlterField(
            model_name='project',
            name='surfaceWaterQualityStandard',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地表水质量标准'),
        ),
        migrations.AlterField(
            model_name='project',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='totalInvestment',
            field=models.FloatField(blank=True, null=True, verbose_name='项目总投资（万元）'),
        ),
        migrations.AlterField(
            model_name='project',
            name='township',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所在区镇'),
        ),
        migrations.AlterField(
            model_name='project',
            name='waterSourceDistance',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='水源保护地距离'),
        ),
        migrations.AlterField(
            model_name='project',
            name='west',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='西'),
        ),
        migrations.AlterField(
            model_name='project',
            name='yearWorkTime',
            field=models.FloatField(blank=True, null=True, verbose_name='年工作时间'),
        ),
    ]
