# Generated by Django 2.0.2 on 2018-03-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180321_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='investmentTime',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='投产时间(年)'),
        ),
    ]
