# Generated by Django 2.0.2 on 2018-03-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180321_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='besideWaterTreatmentPlant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='是否污水处理厂纳污范围'),
        ),
        migrations.AlterField(
            model_name='project',
            name='businessRange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='营业执照经营范围'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contacts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='corporateId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='法人身份证'),
        ),
        migrations.AlterField(
            model_name='project',
            name='corporateName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='法人代表姓名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domesticSewageEmissionStandards',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='生活污水环境影响分析'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domesticSewageEnvironmentImpactAnalysis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='生活污水环境影响分析'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domesticSewageGo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='生活污水去向'),
        ),
        migrations.AlterField(
            model_name='project',
            name='east',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='东 '),
        ),
        migrations.AlterField(
            model_name='project',
            name='groundwaterArea',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地下水区域'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groundwaterBodyNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地下水水体编号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groundwaterQualityStandard',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地下水质量标准'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groundwaterType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地下水类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='investmentTime',
            field=models.FloatField(blank=True, null=True, verbose_name='投产时间(年)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='north',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='北'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pollutantHoldingWaterBody',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='纳污水体'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sensitivePointDistance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='敏感点距离'),
        ),
        migrations.AlterField(
            model_name='project',
            name='soundEnvironmentStandard',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='声环境质量标准'),
        ),
        migrations.AlterField(
            model_name='project',
            name='south',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='南'),
        ),
        migrations.AlterField(
            model_name='project',
            name='specialOptionForSewageTreatmentWorks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='污水处理厂特别选项'),
        ),
        migrations.AlterField(
            model_name='project',
            name='surfaceWaterFunction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地表水功能'),
        ),
        migrations.AlterField(
            model_name='project',
            name='surfaceWaterQualityStandard',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地表水质量标准'),
        ),
        migrations.AlterField(
            model_name='project',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='township',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='所在区镇'),
        ),
        migrations.AlterField(
            model_name='project',
            name='waterSourceDistance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='水源保护地距离'),
        ),
        migrations.AlterField(
            model_name='project',
            name='west',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='西'),
        ),
    ]
