# Generated by Django 2.0.2 on 2018-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180321_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='environmentalProtectionInvestmentProportion',
        ),
        migrations.AlterField(
            model_name='project',
            name='domesticSewageEmissionStandards',
            field=models.TextField(blank=True, null=True, verbose_name='生活污水排放标准'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domesticSewageEnvironmentImpactAnalysis',
            field=models.TextField(blank=True, null=True, verbose_name='生活污水环境影响分析'),
        ),
    ]
